# TODO: Place this file in the .github/workflows folder of your repository
# This sample assumes the working directory is ./samples/get-started
name: Get Started sample
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
         shardIndex: [1, 2, 3, 4]
         shardTotal: [4]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: set up reporting
      working-directory: samples/get-started
      run: |
        npm set //npm.pkg.github.com/:_authToken ${{secrets.PAT_TOKEN_PACKAGE}}
        npm install
        
    - name: Install dependencies
      working-directory: samples/get-started
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: samples/get-started
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: samples/get-started
      env:
        PLAYWRIGHT_SERVICE_ACCESS_TOKEN: ${{secrets.PLAYWRIGHT_SERVICE_ACCESS_TOKEN_REPORTING}}
        PLAYWRIGHT_SERVICE_URL: ${{ secrets.PLAYWRIGHT_SERVICE_URL_REPORTING}}
        PLAYWRIGHT_SERVICE_RUN_ID: ${{ github.run_id }}-${{ github.run_attempt }}-${{ github.sha }}
      #run: npx playwright test --config=playwright.service.config.ts --workers=30 # below is for enabling shard
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} 
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: samples/get-started/playwright-report/
        retention-days: 10

    # - name: Comment on PR
    #   uses: actions/github-script@v5
    #   if: always()
    #   with:
    #     github-token: ${{secrets.GH_TOKEN_FOR_PR_COMMENTS}}
    #     script: |
    #       const issue_number = context.issue.number;
    #       const owner = context.repo.owner;
    #       const repo = context.repo.repo;
    #       const body = 'See test results [here](https://playwright.dev)';
    #       github.rest.issues.createComment({
    #         owner,
    #         repo,
    #         issue_number,
    #         body
    #       });
